name: absensi_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  http: ^1.4.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
